require('functions')

local opts = {noremap = true, silent = true}

--INSERT MODE
vim.api.nvim_set_keymap('i', 'vv', '<Esc>v', opts)
vim.api.nvim_set_keymap('i', 'nn', '<Esc>', opts)
vim.api.nvim_set_keymap('i', 'bb', '<Esc><C-v>', opts)
vim.api.nvim_set_keymap('i', '<C-s>', '<Esc>:wa!<CR>i<Right>', opts)
vim.api.nvim_set_keymap('i', '(', '()<Left>', opts)
vim.api.nvim_set_keymap('i', '[', '[]<Left>', opts)
vim.api.nvim_set_keymap('i', '{', '{}<Left>', opts)
vim.api.nvim_set_keymap('i', '"', '""<Left>', opts)
vim.api.nvim_set_keymap('i', "'", "''<Left>", opts)
vim.api.nvim_set_keymap('i', '<', '<><Left>', opts)
vim.api.nvim_set_keymap('i', '<S-h>', '<Left>', opts)
vim.api.nvim_set_keymap('i', '<S-l>', '<Right>', opts)
vim.api.nvim_set_keymap('i', '<S-j>', '<Down>', opts)
vim.api.nvim_set_keymap('i', '<S-k>', '<Up>', opts)
vim.api.nvim_set_keymap('i', 'hh', 'H', opts)
vim.api.nvim_set_keymap('i', 'jj', 'J', opts)
vim.api.nvim_set_keymap('i', 'kk', 'K', opts)
vim.api.nvim_set_keymap('i', 'll', 'L', opts)
vim.api.nvim_set_keymap('i', '<C-l>', '<Delete>', opts)
vim.api.nvim_set_keymap('i', '<Tab>', '    ', opts)
vim.api.nvim_set_keymap('i', '<S-Tab>', '<Esc><S-<><S-<>i', opts)
vim.api.nvim_set_keymap('i', '<C-k>', '<Esc>o', opts)
vim.api.nvim_set_keymap('i', '<C-j>', '<Esc><S-o>', opts)
vim.api.nvim_set_keymap('i', 'ee', '<CR>', opts)

--VIEW MODE    
vim.api.nvim_set_keymap('v', 'ii', '<Esc>i', opts)
vim.api.nvim_set_keymap('v', 'nn', '<Esc>', opts)
vim.api.nvim_set_keymap('v', 'bb', '<Esc><C-v>', opts)
vim.api.nvim_set_keymap('v', 'r', 'di', opts)
vim.api.nvim_set_keymap('v', '<', '<gv', opts)
vim.api.nvim_set_keymap('v', '>', '>gv', opts)
vim.api.nvim_set_keymap('v', '<CR>', 'i', opts)
vim.api.nvim_set_keymap('v', '<C-k>', ':m -2<CR>==gv', opts)
vim.api.nvim_set_keymap('v', '<C-j>', [[:'<,'>m '>+1<CR>==gv]], opts)

--NORMAL MODE  
vim.api.nvim_set_keymap('n', '<C-y>', 'b', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<C-u>', 'w', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<C-n>', '<C-u>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<C-m>', '<C-d>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'term', ':lua Terminal()<CR>i', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'bb', '<Esc><C-v>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'r', '<C-r><CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'ct', ':lcd %:p:h<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'cb', ':lct<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'ter', ':terminal<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'nn', ':lua LocalTree()<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'nb', ':lua ConfigTree()<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'nm', ':lua MicroservicesTree()<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<Left>', '<Esc>:vertical resize -2<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<Up>', '<Esc>:resize +2<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<Down>', '<Esc>:resize -2<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<Right>', '<Esc>:vertical resize +2<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<C-v>', '<Esc>:vsplit<CR>i', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<C-b>', '<Esc>:split<CR>i', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<C-k>', '<S-n>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<C-j>', 'n', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'mvnw', ':lua Mvnw()<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'run', ':lua Run_dev()<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'build', ':lua Build()<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'push', ':lua Push()<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<C-p>', ':UndotreeToggle<CR><Tab>', {noremap = true, silent = true})

--LEADER STUFF   
vim.api.nvim_set_keymap('n', '<leader>d', ':lua require("telescope").extensions.live_grep_args.live_grep_args({ cwd = Path_global})<CR>', opts)
vim.api.nvim_set_keymap('n', '<leader>g', ':LazyGitCurrentFile<CR>', opts)
vim.api.nvim_set_keymap('n', '<leader>l', ':Lazy<CR>', opts)
vim.api.nvim_set_keymap('n', '<leader>k', ':Mason<CR>', opts)
vim.api.nvim_set_keymap('n', '<leader>j', ':lua Find_files_local()<CR>', opts)
vim.api.nvim_set_keymap('n', '<leader>h', ':Telescope find_files hidden=true no_ignore=true<CR>', opts)
vim.api.nvim_set_keymap('n', '<leader>a', 'za', opts)
vim.api.nvim_set_keymap('v', '<leader>f', 'zf', opts)

--LSP STUFF
vim.api.nvim_set_keymap('n', 'imp', ':lua vim.lsp.buf.implementation()<CR>', opts)
vim.api.nvim_set_keymap('n', 'desc', ':lua vim.lsp.buf.hover()<CR>', opts)
vim.api.nvim_set_keymap('n', 'refs', ':lua vim.lsp.buf.references()<CR>', opts)
vim.api.nvim_set_keymap('n', 'err', ':lua vim.diagnostic.open_float()<CR>', opts)
vim.api.nvim_set_keymap('n', 'en', ':lua vim.diagnostic.goto_next({buffer=0})<CR>', opts)
vim.api.nvim_set_keymap('n', 'ep', ':lua vim.diagnostic.goto_prev({buffer=0})<CR>', opts)
vim.api.nvim_set_keymap('n', 'rnm', ':lua vim.lsp.buf.rename()<CR>', opts)
vim.api.nvim_set_keymap('n', 'act', ':lua vim.lsp.buf.code_action()<CR>', opts)
